export const RESET_ERRORS = 'RESET_ERRORS';

export const ITEMS_LOCKED = 'ITEMS_LOCKED';
export const ITEMS_LOADED = 'ITEMS_LOADED';
export const ITEMS_FAILED = 'ITEMS_FAILED';

export const SWITCH_TAB = 'SWITCH_TAB';
export const CLOSE_TAB = 'CLOSE_TAB';
export const CLOSE_TABS = 'CLOSE_TABS';
export const TAB_ID_NOT_FOUND = 'TAB_ID_NOT_FOUND';
export const TAB_INDEX_NOT_FOUND = 'TAB_INDEX_NOT_FOUND';
export const TAB_OPEN_EXCEPTION = 'TAB_OPEN_EXCEPTION';
export const TAB_CLOSE_EXCEPTION = 'TAB_CLOSE_EXCEPTION';
